description: >
  Dynamically generate pipeline config

usage:
  # .circleci/config.yml
  version: '2.1'
  setup: true

  orbs:
    rusty: bencord0/rusty-orb@1.1.0

  jobs:
    setup:
      ...
      steps:
        - checkout
        - run:
            name: Generate Config
            command:
              ./generate_config.py > generated-config/config.yml
              ./generate_params.py > generated-config/parameters.yml
        - persist_to_workspace:
            root: .
            paths:
              - generated-config

  workflows:
    setup:
      jobs:
      - setup
      - rusty/continue
          configuration: ./generated-config/config.yml
          parameters: ./generated-config/parameters.yml
          requires:
            - setup

  # ./generated-config/config.yml
  version: '2.1'

  parameters:
    my_parameter:
      type: string
      default: "FOO!"

  jobs:
    my_job:
      ...

  workflows:
    my_workflow:
      jobs:
        - my_job:
            my_parameter: << pipeline.parameters.my_parameter >>

  # ./generated-config/parameters.yml
  my_parameter: foo
  ```
